-- University of the Philippines Diliman (UPD) Data
-- Reference: https://upd.edu.ph/about-up-diliman/
-- Programs Reference: https://upd.edu.ph/academics/

INSERT INTO universities (
  name, location, province, established, type, students, programs,
  description, long_description, subjects, image_url, gallery_images,
  accreditation, campus_size, founded, website, phone, email, address,
  facilities, amenities, achievements, quickfacts, admission_requirements, application_process, admission_status, admission_deadline,
  academic_semester_start, academic_semester_end, academic_application_deadline,
  ranking_source, ranking_details, map_location_lat, map_location_lng
) VALUES (
  'University of the Philippines Diliman',
  'Quezon City',
  'Metro Manila',
  '1949', -- established (year)
  'Public',
  '22000', -- students (as string)
  247, -- programs
  'The flagship campus of the University of the Philippines System, offering a wide range of undergraduate and graduate programs.',
  'The University of the Philippines Diliman, coeval with the University of the Philippines, was established on June 18, 1908 through Act No. 1870 of the Philippine Assembly. The university was created to provide advanced instruction in literature, philosophy, the sciences, and arts, and to give professional and technical training to deserving students.',
  ARRAY['Architecture', 'Business Administration', 'Education', 'Engineering', 'Fine Arts', 'Home Economics', 'Library and Information Science', 'Mass Communication', 'Music', 'Public Administration', 'Science', 'Social Sciences and Philosophy', 'Social Work', 'Statistics', 'Economics', 'Human Kinetics', 'Islamic Studies', 'Labor and Industrial Relations', 'Law', 'Tourism']::text[], -- subjects
  'https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg', -- image_url (first from gallery)
  ARRAY['https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg', 'https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg', 'https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg', 'https://zdixoeqnifczswpxospm.supabase.co/storage/v1/object/public/Images/PUP%20images/PLACEHOLDER.jpg']::text[], -- gallery_images
  ARRAY['Most of its programs are recognized as Centers of Excellence and Centers of Development by the Commission on Higher Education.']::text[], -- accreditation
  '493-hectare', -- campus_size (extracted from long_description)
  '1908', -- founded (extracted from long_description)
  'https://upd.edu.ph/',
  'info.upd@up.edu.ph',
  '(02) 8981 8500',
  'Diliman, Quezon City, Metro Manila',
  ARRAY['University Library', 'Vargas Museum', 'University Theater', 'Academic Oval', 'Sports facilities', 'Computer Laboratories', 'Research Centers']::text[], -- facilities
  ARRAY['Dormitories', 'Cafeterias', 'Health service', 'Student union building', 'Parking', 'Shuttle Service']::text[], -- amenities
  ARRAY['Produced numerous national leaders, artists, scientists, and entrepreneurs.']::text[], -- achievements
  ARRAY['The campus is a sprawling 493-hectare site, a declared National Historical Landmark.']::text[], -- quickfacts
  ARRAY[
    'GENERAL REQUIREMENTS',
    'Must be a graduate of a high school accredited by the Department of Education.',
    'Must pass the UP College Admission Test (UPCAT).'
  ]::text[], -- admission_requirements
  ARRAY[
    'Submit an online application through the UPCAT portal.',
    'Pay the application fee.',
    'Take the UPCAT exam on the scheduled date.',
    'Wait for the release of the UPCAT results.'
  ]::text[], -- application_process
  'Varies', -- admission_status
  NULL, -- admission_deadline
  NULL, -- academic_semester_start
  NULL, -- academic_semester_end
  NULL, -- academic_application_deadline
  'QS World University Rankings 2024', -- ranking_source
  'Ranked #1 in the Philippines and #404 in the world.', -- ranking_details
  14.6539, -- map_location_lat
  121.0685 -- map_location_lng
);

INSERT INTO academic_programs (university_id, program_name, college_name, program_type, degree_level, specializations)
VALUES
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Landscape Architecture', 'College of Architecture', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Architecture', 'College of Architecture', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Business Administration', 'College of Business Administration', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Business Administration and Accountancy', 'College of Business Administration', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Elementary Education', 'College of Education', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Secondary Education', 'College of Education', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Civil Engineering', 'College of Engineering', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Chemical Engineering', 'College of Engineering', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Computer Science', 'College of Engineering', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Electrical Engineering', 'College of Engineering', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Electronics & Communications Engineering', 'College of Engineering', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Geodetic Engineering', 'College of Engineering', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Industrial Engineering', 'College of Engineering', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Mechanical Engineering', 'College of Engineering', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Metallurgical Engineering', 'College of Engineering', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Mining Engineering', 'College of Engineering', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Materials Engineering', 'College of Engineering', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Computer Engineering', 'College of Engineering', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Fine Arts', 'College of Fine Arts', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Interior Design', 'College of Home Economics', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Library & Information Science', 'School of Library and Information Studies', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts in Broadcast Communication', 'College of Mass Communication', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts in Journalism', 'College of Mass Communication', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts in Communication Research', 'College of Mass Communication', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts in Film', 'College of Mass Communication', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Music', 'College of Music', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Public Administration)', 'National College of Public Administration and Governance', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Biology', 'College of Science', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Chemistry', 'College of Science', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Mathematics', 'College of Science', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Molecular Biology & Biotechnology', 'College of Science', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Geology', 'College of Science', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Applied Physics', 'College of Science', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Physics', 'College of Science', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Anthropology)', 'College of Social Sciences and Philosophy', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science (Geography)', 'College of Social Sciences and Philosophy', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (History)', 'College of Social Sciences and Philosophy', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Linguistics)', 'College of Social Sciences and Philosophy', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Philosophy)', 'College of Social Sciences and Philosophy', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Political Science)', 'College of Social Sciences and Philosophy', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Psychology)', 'College of Social Sciences and Philosophy', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science (Psychology)', 'College of Social Sciences and Philosophy', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Sociology)', 'College of Social Sciences and Philosophy', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Community Development', 'College of Social Work and Community Development', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Social Work', 'College of Social Work and Community Development', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science (Statistics)', 'School of Statistics', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Business Economics)', 'School of Economics', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Applied Psychology)', 'College of Social Sciences and Philosophy', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Business Management', 'College of Business Administration', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Art Studies)', 'College of Arts and Letters', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Comparative Literature)', 'College of Arts and Letters', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Creative Writing)', 'College of Arts and Letters', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (English Studies)', 'College of Arts and Letters', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (European Languages)', 'College of Arts and Letters', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Araling Pilipino)', 'College of Arts and Letters', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Filipino)', 'College of Arts and Letters', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Malikhaing Pagsulat sa Filipino)', 'College of Arts and Letters', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Speech Communication)', 'College of Arts and Letters', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Arts (Theatre Arts)', 'College of Arts and Letters', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Tourism', 'Asian Institute of Tourism', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Business Economics', 'School of Economics', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Economics', 'School of Economics', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Clothing Technology', 'College of Home Economics', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Family Life & Child Development', 'College of Home Economics', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Community Nutrition', 'College of Home Economics', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Food Technology', 'College of Home Economics', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Home Economics', 'College of Home Economics', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Science in Hotel, Restaurant & Institution Management', 'College of Home Economics', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Physical Education', 'College of Human Kinetics', 'undergraduate', 'Bachelors', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Bachelor of Sports Science', 'College of Human Kinetics', 'undergraduate', 'Bachelors', NULL);

-- UPD Graduate Programs
INSERT INTO academic_programs (university_id, program_name, college_name, program_type, degree_level, specializations)
VALUES
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Architecture', 'College of Architecture', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Tropical Landscape Architecture', 'College of Architecture', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Art Studies)', 'College of Arts and Letters', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master in Philippine Studies', 'Asian Center', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master in Asian Studies', 'Asian Center', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts in Asian Studies', 'Asian Center', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts in Philippine Studies', 'Asian Center', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Comparative Literature)', 'College of Arts and Letters', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Creative Writing)', 'College of Arts and Letters', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (English Studies)', 'College of Arts and Letters', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Speech Communication)', 'College of Arts and Letters', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Theatre Arts)', 'College of Arts and Letters', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Business Administration', 'College of Business Administration', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Finance', 'College of Business Administration', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Management', 'College of Business Administration', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (French Language)', 'College of Arts and Letters', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (German)', 'College of Arts and Letters', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Spanish)', 'College of Arts and Letters', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Araling Pilipino)', 'College of Arts and Letters', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Filipino)', 'College of Arts and Letters', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master in Development Economics', 'School of Economics', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Economics)', 'School of Economics', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts in Education', 'College of Education', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Civil Engineering', 'College of Engineering', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Chemical Engineering', 'College of Engineering', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Engineering in Electrical Engineering', 'College of Engineering', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Electrical Engineering', 'College of Engineering', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Computer Science', 'College of Engineering', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Geomatics Engineering', 'College of Engineering', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Industrial Engineering', 'College of Engineering', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Mechanical Engineering', 'College of Engineering', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Materials Science & Engineering)', 'College of Engineering', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Metallurgical Engineering', 'College of Engineering', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Energy Engineering', 'College of Engineering', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Environmental Engineering', 'College of Engineering', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Interior Design', 'College of Home Economics', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Fine Arts', 'College of Fine Arts', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Family Life & Child Development', 'College of Home Economics', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Food Service Administration', 'College of Home Economics', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Food Science)', 'College of Home Economics', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Nutrition)', 'College of Home Economics', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Home Economics', 'College of Home Economics', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Human Movement Science', 'College of Human Kinetics', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Islamic Studies)', 'Institute of Islamic Studies', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Industrial Relations', 'School of Labor and Industrial Relations', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Juris Doctor', 'College of Law', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Library & Information Science', 'School of Library and Information Studies', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Communication: Communication Research)', 'College of Mass Communication', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts in Media Studies (Broadcasting, Film, Journalism)', 'College of Mass Communication', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Music', 'College of Music', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Public Administration', 'National College of Public Administration and Governance', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Biology)', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Chemical Education)', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Chemistry)', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Environmental Science)', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Meteorology)', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Mathematics)', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Applied Mathematics)', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Mathematics', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Professional Master''s in Applied Mathematics', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Microbiology)', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Molecular Biology & Biotechnology)', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Marine Science)', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Geology)', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Physics)', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Physics)', 'College of Science', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Anthropology)', 'College of Social Sciences and Philosophy', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Geography)', 'College of Social Sciences and Philosophy', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (History)', 'College of Social Sciences and Philosophy', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Linguistics)', 'College of Social Sciences and Philosophy', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Bioethics', 'College of Social Sciences and Philosophy', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Philosophy)', 'College of Social Sciences and Philosophy', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts Honors (Political Science)', 'College of Social Sciences and Philosophy', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master in International Studies', 'College of Social Sciences and Philosophy', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Political Science)', 'College of Social Sciences and Philosophy', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Psychology)', 'College of Social Sciences and Philosophy', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Sociology)', 'College of Social Sciences and Philosophy', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master in Population Studies', 'College of Social Sciences and Philosophy', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Demography)', 'College of Social Sciences and Philosophy', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Community Development', 'College of Social Work and Community Development', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Social Work', 'College of Social Work and Community Development', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Women & Development)', 'College of Social Work and Community Development', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Statistics', 'School of Statistics', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Statistics)', 'School of Statistics', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Urban & Regional Planning)', 'School of Urban and Regional Planning', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science in Regional Development Planning', 'School of Urban and Regional Planning', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Management', 'College of Business Administration', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Arts (Archaeology)', 'Archaeological Studies Program', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Science (Archaeology)', 'Archaeological Studies Program', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Master of Technology Management', 'Technology Management Center', 'graduate', 'Masters', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Biology)', 'College of Science', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Chemistry)', 'College of Science', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Environmental Science)', 'College of Science', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Meteorology)', 'College of Science', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Mathematics)', 'College of Science', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Molecular Biology & Biotechnology)', 'College of Science', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Marine Science)', 'College of Science', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Geology)', 'College of Science', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Materials Science & Engineering)', 'College of Engineering', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Physics)', 'College of Science', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Anthropology)', 'College of Social Sciences and Philosophy', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (History)', 'College of Social Sciences and Philosophy', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Linguistics)', 'College of Social Sciences and Philosophy', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy in Philosophy', 'College of Social Sciences and Philosophy', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Political Science)', 'College of Social Sciences and Philosophy', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Psychology)', 'College of Social Sciences and Philosophy', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Sociology)', 'College of Social Sciences and Philosophy', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor in Social Development', 'College of Social Work and Community Development', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Statistics)', 'School of Statistics', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy in Urban & Regional Planning', 'School of Urban and Regional Planning', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy in Archaeology', 'Archaeological Studies Program', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Philippine Studies)', 'Asian Center', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Comparative Literature)', 'College of Arts and Letters', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Creative Writing)', 'College of Arts and Letters', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (English Studies)', 'College of Arts and Letters', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Business Administration)', 'College of Business Administration', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Filipino)', 'College of Arts and Letters', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Hispanic Literature)', 'College of Arts and Letters', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Economics)', 'School of Economics', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy in Education', 'College of Education', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Civil Engineering)', 'College of Engineering', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Engineering (Chemical Engineering)', 'College of Engineering', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Chemical Engineering)', 'College of Engineering', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Engineering (Electrical & Electronics Engineering)', 'College of Engineering', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Electrical & Electronics Engineering)', 'College of Engineering', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Energy Engineering)', 'College of Engineering', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Environmental Engineering)', 'College of Engineering', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Food Science)', 'College of Home Economics', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Nutrition)', 'College of Home Economics', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Philosophy (Communication)', 'College of Mass Communication', 'graduate', 'Doctorate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Doctor of Public Administration', 'National College of Public Administration and Governance', 'graduate', 'Doctorate', NULL);

-- UPD Diploma Programs
INSERT INTO academic_programs (university_id, program_name, college_name, program_type, degree_level, specializations)
VALUES
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Industrial Relations', 'School of Labor and Industrial Relations', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Librarianship', 'School of Library and Information Studies', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Creative & Performing Musical Arts', 'College of Music', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Ethnomusicology', 'College of Music', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Public Management', 'National College of Public Administration and Governance', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Voluntary Sector Management', 'National College of Public Administration and Governance', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Biology', 'College of Science', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Chemistry', 'College of Science', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Environmental Science', 'College of Science', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Meteorology', 'College of Science', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Mathematics', 'College of Science', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Physics', 'College of Science', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Bioethics', 'College of Social Sciences and Philosophy', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Community Development', 'College of Social Work and Community Development', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Community Organizing', 'College of Social Work and Community Development', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Social Work', 'College of Social Work and Community Development', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Women & Development', 'College of Social Work and Community Development', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Urban & Regional Planning', 'School of Urban and Regional Planning', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Archaeology', 'Archaeological Studies Program', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Technology Management', 'Technology Management Center', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Remote Sensing', 'College of Engineering', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Early Childhood Development', 'College of Education', 'diploma', 'Diploma', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Diploma in Exercise and Sport Sciences', 'College of Human Kinetics', 'diploma', 'Diploma', NULL);

-- UPD Certificate Programs
INSERT INTO academic_programs (university_id, program_name, college_name, program_type, degree_level, specializations)
VALUES
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Certificate in Building Technology', 'College of Architecture', 'diploma', 'Certificate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Certificate in Theater Arts (Performance; Technical Theater & Management)', 'College of Arts and Letters', 'diploma', 'Certificate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Sertipiko sa Malikhaing Pagsulat sa Filipino', 'College of Arts and Letters', 'diploma', 'Certificate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Certificate in Theatre Arts', 'College of Arts and Letters', 'diploma', 'Certificate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Certificate in Sports Studies', 'College of Human Kinetics', 'diploma', 'Certificate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Certificate in Fine Arts (Painting, Sculpture, Industrial Design, Visual Communication)', 'College of Fine Arts', 'diploma', 'Certificate', NULL),
  ((SELECT id from universities where name = 'University of the Philippines Diliman'), 'Certificate in Music', 'College of Music', 'diploma', 'Certificate', NULL);